spring:
  profiles:
    active: @profiles.active@
  application:
    name: saasDataStore
server:
  port: 8081
  servlet:
    context-path: /saasDataStore

mybais:
#  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xiangying.saas.data.store.model.*